POST http://localhost:1323/study-notes/api/note/new
Content-Type: application/json
# POSTとContent-Typeの間に改行を入れない

{
  "title":"Hello",
  "content":"hogehoge",
  "updated_at":"2026-04-27T09:00:00Z",
  "created_at":"2026-04-27T09:00:00Z"
}
