services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace
    volumes:
      - ..:/workspace:cached
      - f-node_modules:/workspace/frontend/node_modules
    command: sleep infinity
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

volumes:
 f-node_modules:
