services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace
    volumes:
      - ..:/workspace:cached
      - f-node_modules:/workspace/frontend/node_modules
      - b-go_mod:/go/pkg/mod
    command: sleep infinity
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=study-notes
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
volumes:
  f-node_modules:
  b-go_mod:
  pgdata:
